apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  selector:
     matchLabels:
       role: web-frontend
  template:
     metadata:
       labels:
         role: web-frontend
     spec:
       containers:
       - name: web
         image: nginx
         envFrom:
           - configMapRef:
                 name: my-config
