apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      role: web-frontend
  template:
    metadata:
      labels:
        role: web-frontend
    spec:
      containers:
      - name: web
        image: nginx
        ports:
         - name: web
           containerPort: 80
        volumeMounts:
           - name: data
             mountPath: "/etc/data"
      volumes:
      - name: data
        configMap:
           name: my-config
